### ISSUE TITLE
Importing TV Shows displays invalid date

### ISSUE THREAD

**Issue by JegorRysskin** [PixelPusher247/tvtime2trakt#1]
I'm assuming the date shown is the watched date, it appears the date is not correctly being interpreted.
![image](https://github.com/PixelPusher247/tvtime2trakt/assets/24411845/29c67ac7-63dd-4a30-8d06-c416c934edc4)

**Comment by PixelPusher247** [comment]
When did you receive your data from TV Time? They might have fixed their issue with dates looking all botched and having to be interpreted. What do the values in the column `created_at` in `tracking-prod-records-v2.csv` look like? Do they look like: `52735365-10-07 19:52:37` or like an actual date that makes sense?

**Comment by JegorRysskin** [comment]
Both of the created_at and updated_at in tracking-prod-records-v2.csv look like a regular date that makes sense like: 23/12/2022  15:02:58 and 06/12/2022  14:46:59

**Comment by PixelPusher247** [comment]
Updated to use `DateTime.Parse` given that TV Time now exports parseable dates.
Let me know if the import works for you!

**Comment by JegorRysskin** [comment]
Yup works great now! Thanks!
